import './globals.css';
import  Providers  from '../features/Providers'; // Assuming Providers.jsx is in this path

export const metadata = {
  title: 'Your App Title',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}